const TOTAL=5, EPS=.001; let lang='zh',subject='none',questions=[],answers=[],current=0,graded=false; const banks={math:null,english:null,science:null};
const T={zh:{brand:'知途学苑',logo:'知',pageTitle:'知途学苑 - 智能学习系统',heroKicker:'共行学习路径',heroTitle:'每一道题，都让学习',heroEm:'更进一步。',heroCopy:'从小学到高中，用短小、专注的分级练习建立真实可见的学习进步。',heroReady:'✓ 题库已就绪',heroRound:'每轮 5 题',heroSubjects:'数学 · 英语 · 科学',heroSteps:'练习 · 打牢基础 · 掌握',home:'选择学习路径',sub:'数学、英语与科学分级题库均已接入。',math:'数学',english:'英语',science:'科学',mathDesc:'数感、代数、几何与分级拓展题。',englishDesc:'词义、语法、阅读与主题词汇拓展。',scienceDesc:'从生命科学到物理、化学的探索。',cardAction:'开始学习 →',start:'开始刷题',prev:'上一题',next:'下一题',submit:'提交批改',today:'今日已刷(题)',accuracy:'平均正确率',streak:'连续打卡(天) 🔥',points:'学习积分 ✦',titlesKicker:'称号',titles:'成就称号',game:'受控休息区',gameSub:'完成学习后，用积分安排有上限的休息时间',pointUnit:'积分',note:'每次最多随机抽取 5 道不重复题目；题量不足时按实际题数测试。',placeholder:'输入答案',correct:'✔️ 回答正确！',wrong:a=>`❌ 回答错误。正确答案：${a}`,empty:a=>`⚠️ 未作答。正确答案：${a}`,score:(c,n)=>`测试完成！答对 ${c} 题，共 ${n} 题 🔥 数据已保存！`,types:{number:'请输入数字答案：',meaning:'选出下列单词的正确词义：',synonym:'选出最接近的近义词：',grammar:'选择正确的选项填空：',reading:'阅读理解：根据短文回答问题。',mc:'选择正确的答案：'}},en:{brand:'Zhitu Academy',logo:'Z',pageTitle:'Zhitu Academy - Smart Learning System',heroKicker:'Shared Learning Path',heroTitle:'Every question moves learning',heroEm:'one step forward.',heroCopy:'From elementary school to high school, focused level-based practice makes progress clear and visible.',heroReady:'✓ Banks ready',heroRound:'5 questions per round',heroSubjects:'Math · English · Science',heroSteps:'Practice · Foundation · Mastery',home:'Choose a learning path',sub:'Graded Math, English, and Science question banks are ready.',math:'Mathematics',english:'English',science:'Science',mathDesc:'Number sense, algebra, geometry, and leveled extension problems.',englishDesc:'Word meanings, grammar, reading, and themed vocabulary growth.',scienceDesc:'Explore life science, physics, chemistry, and scientific reasoning.',cardAction:'Start learning →',start:'Start Quiz',prev:'Previous',next:'Next',submit:'Submit & Grade',today:'Today Solved',accuracy:'Average Accuracy',streak:'Streak (days) 🔥',points:'Learning points ✦',titlesKicker:'TITLES',titles:'Titles & Achievements',game:'Controlled break',gameSub:'After learning, use points for a time-limited break',pointUnit:'points',note:'Each quiz selects up to 5 unique questions. Smaller banks use their available question count.',placeholder:'Enter answer',correct:'✔️ Correct!',wrong:a=>`❌ Wrong. Correct answer: ${a}`,empty:a=>`⚠️ No answer. Correct answer: ${a}`,score:(c,n)=>`Quiz completed! Score: ${c} / ${n} 🔥 Stats saved!`,types:{number:'Enter the numeric answer:',meaning:'Choose the correct meaning:',synonym:'Choose the closest synonym:',grammar:'Choose the correct word:',reading:'Read the passage and answer:',mc:'Choose the correct answer:'}}};
T.zh.note='每次最多随机抽取 5 道不重复题目；题量不足时按实际题数测试。';T.en.note='Each quiz selects up to 5 unique questions. Smaller banks use their available question count.';
Object.assign(T.zh,{brand:'学会啦',logo:'会',pageTitle:'学会啦 - 智能学习系统',backToSetup:'← 返回课程',backHome:'← 返回学习首页'});
Object.assign(T.en,{brand:'Got It Learning',logo:'G',pageTitle:'Got It Learning - Smart Learning System',backToSetup:'← Back to courses',backHome:'← Back to learning home'});
Object.assign(T.zh,{heroEm:'更进一步',heroCopy:'从小学到高中，用短小、专注的分级练习建立真实可见的学习进步',sub:'数学、英语与科学分级题库均已接入',mathDesc:'数感、代数、几何与分级拓展题',englishDesc:'词义、语法、阅读与主题词汇拓展',scienceDesc:'从生命科学到物理、化学的探索'});
Object.assign(T.en,{heroEm:'one step forward',heroCopy:'From elementary school to high school, focused level-based practice makes progress clear and visible',sub:'Graded Math, English, and Science question banks are ready',mathDesc:'Number sense, algebra, geometry, and leveled extension problems',englishDesc:'Word meanings, grammar, reading, and themed vocabulary growth',scienceDesc:'Explore life science, physics, chemistry, and scientific reasoning'});
const DEFAULT_ARCADE_GAME_COUNT=8;
let arcadeGameCount=DEFAULT_ARCADE_GAME_COUNT;
Object.assign(T.zh,{gameSub:'完成学习后，用积分安排有上限的休息时间',usageTitle:'查看使用记录',usageSub:'今日与本周 · 学习时长、休息时长和课程阶段'});
Object.assign(T.en,{gameSub:'After learning, use points for a time-limited break',usageTitle:'View usage records',usageSub:'Today and this week · learning, break time, and course stages'});
const ACHIEVEMENTS=[
{id:'first_step',icon:'🌱',zh:'初出茅庐',en:'First Step',zhDesc:'完成第一次测试',enDesc:'Complete your first quiz',tierZh:'旅程 · I',tierEn:'JOURNEY · I',style:'wilderness',silhouette:'启',art:'assets/titles/first-step.jpg',test:u=>u.quizCount>=1},
{id:'ten_solved',icon:'🥉',zh:'青铜学徒',en:'Bronze Learner',zhDesc:'累计完成 10 题',enDesc:'Solve 10 questions',tierZh:'锻造 · II',tierEn:'FORGED · II',style:'bronze',silhouette:'铸',art:'assets/titles/bronze-apprentice.jpg',test:u=>u.totalSolved>=10},
{id:'fifty_solved',icon:'🥈',zh:'白银探索者',en:'Silver Explorer',zhDesc:'累计完成 50 题',enDesc:'Solve 50 questions',tierZh:'远征 · III',tierEn:'EXPEDITION · III',style:'silver',silhouette:'征',art:'assets/titles/silver-explorer.jpg',test:u=>u.totalSolved>=50},
{id:'hundred_solved',icon:'🥇',zh:'黄金学者',en:'Golden Scholar',zhDesc:'累计完成 100 题',enDesc:'Solve 100 questions',tierZh:'典藏 · IV',tierEn:'ARCHIVE · IV',style:'gold',silhouette:'典',art:'assets/titles/golden-scholar.jpg',test:u=>u.totalSolved>=100},
{id:'three_hundred',icon:'👑',zh:'天下无双',en:'Peerless',zhDesc:'累计完成 300 题',enDesc:'Solve 300 questions',tierZh:'传说 · V',tierEn:'MYTHIC · V',style:'mythic',silhouette:'冠',art:'assets/titles/peerless.jpg',test:u=>u.totalSolved>=300},
{id:'accuracy_80',icon:'🎯',zh:'稳定发挥',en:'Steady Aim',zhDesc:'完成至少 20 题且正确率达到 80%',enDesc:'Reach 80% accuracy after 20 questions',tierZh:'战术 · III',tierEn:'TACTICAL · III',style:'marksman',silhouette:'衡',art:'assets/titles/steady.jpg',test:u=>u.totalSolved>=20&&u.totalCorrect/u.totalSolved>=.8},
{id:'accuracy_95',icon:'💎',zh:'精准大师',en:'Precision Master',zhDesc:'完成至少 50 题且正确率达到 95%',enDesc:'Reach 95% accuracy after 50 questions',tierZh:'极致 · V',tierEn:'PRECISION · V',style:'crystal',silhouette:'准',art:'assets/titles/precision.jpg',test:u=>u.totalSolved>=50&&u.totalCorrect/u.totalSolved>=.95},
{id:'perfect_quiz',icon:'💯',zh:'满分时刻',en:'Perfect Run',zhDesc:'获得一次测试满分',enDesc:'Earn a perfect quiz score',tierZh:'日蚀 · IV',tierEn:'ECLIPSE · IV',style:'eclipse',silhouette:'满',art:'assets/titles/perfect.jpg',test:u=>u.perfectQuizzes>=1},
{id:'math_master',icon:'📐',zh:'算道天枢',en:'Celestial Calculus',zhDesc:'数学累计答对 150 题',enDesc:'Answer 150 math questions correctly',tierZh:'星轨 · V',tierEn:'CELESTIAL · V',style:'astral',silhouette:'算',art:'assets/titles/math-master.jpg',test:u=>u.mastery.math>=150},
{id:'english_master',icon:'📝',zh:'万言鼎宗',en:'Master of Myriad Words',zhDesc:'英语累计答对 150 题',enDesc:'Answer 150 English questions correctly',tierZh:'墨卷 · V',tierEn:'INKBOUND · V',style:'ink',silhouette:'文',art:'assets/titles/english-master.jpg',test:u=>u.mastery.english>=150},
{id:'science_master',icon:'🔬',zh:'星衡探元',en:'Stellar Origin Seeker',zhDesc:'科学累计答对 150 题',enDesc:'Answer 150 science questions correctly',tierZh:'观测 · V',tierEn:'OBSERVATORY · V',style:'observatory',silhouette:'探',art:'assets/titles/science-master.jpg',test:u=>u.mastery.science>=150},
{id:'all_rounder',icon:'🌈',zh:'全科选手',en:'All-Rounder',zhDesc:'三科分别累计答对 20 题',enDesc:'Answer 20 questions correctly in every subject',tierZh:'棱镜 · IV',tierEn:'PRISM · IV',style:'prism',silhouette:'全',art:'assets/titles/all-rounder.jpg',test:u=>Math.min(u.mastery.math,u.mastery.english,u.mastery.science)>=20},
{id:'streak_3',icon:'🔥',zh:'坚持不懈',en:'On Fire',zhDesc:'连续学习 3 天',enDesc:'Maintain a 3-day streak',tierZh:'余烬 · II',tierEn:'EMBER · II',style:'ember',silhouette:'恒',art:'assets/titles/streak-3.jpg',test:u=>u.streak>=3},
{id:'streak_7',icon:'⚡',zh:'一周连胜',en:'Week Warrior',zhDesc:'连续学习 7 天',enDesc:'Maintain a 7-day streak',tierZh:'破晓 · IV',tierEn:'DAWN · IV',style:'storm',silhouette:'胜',art:'assets/titles/streak-7.jpg',test:u=>u.streak>=7},
{id:'streak_30',icon:'🏆',zh:'月度传奇',en:'Monthly Legend',zhDesc:'连续学习 30 天',enDesc:'Maintain a 30-day streak',tierZh:'永恒 · V',tierEn:'ETERNAL · V',style:'legend',silhouette:'永',art:'assets/titles/streak-30.jpg',test:u=>u.streak>=30}
];
const ADMIN_SETTINGS_KEY='wuming_admin_settings_v1',ADMIN_ACTIVE_KEY='wuming_admin_active_v1',DEFAULT_POINT_CAP=999999,DEFAULT_GAME_MINUTES=15,MAX_GAME_MINUTES=60,DEFAULT_DAILY_LESSON_GOAL=2,DEFAULT_DAILY_PLAY_MINUTES=20,USAGE_KEY='wuming_usage_log_v1';
let adminActive=sessionStorage.getItem(ADMIN_ACTIVE_KEY)==='true',adminSettings={pointCap:DEFAULT_POINT_CAP,freeGames:false,gameMinutesCap:DEFAULT_GAME_MINUTES,dailyLessonGoal:DEFAULT_DAILY_LESSON_GOAL,dailyPlayMinutesCap:DEFAULT_DAILY_PLAY_MINUTES,allowedLevels:{math:[],english:[],science:[]}},quizStartedAt=0,usageRange='today'; let user={totalSolved:0,totalCorrect:0,todaySolved:0,lastDate:'',streak:0,mastery:{math:0,english:0,science:0},knowledgeMastery:{},reviewSchedule:{},lessonRewards:{},dailyLessons:{},lastCourse:null,wrongBook:[],quizCount:0,perfectQuizzes:0,unlockedAchievements:[],achievementUnlockedAt:{},seenAchievementReveals:[],equippedTitle:'',points:0,lifetimePointsEarned:0,pointHistory:[]};
const tx=x=>typeof x==='object'?(x[lang]||x.zh||x.en||''):String(x??''); const clone=x=>JSON.parse(JSON.stringify(x)); const shuffle=a=>[...a].sort(()=>Math.random()-.5);
