function localDay(date=new Date()){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`}
function readUsage(){try{const saved=JSON.parse(localStorage.getItem(USAGE_KEY)||'{}');return{days:saved.days&&typeof saved.days==='object'?saved.days:{},events:Array.isArray(saved.events)?saved.events:[]}}catch{return{days:{},events:[]}}}
function writeUsage(log){const cutoff=new Date();cutoff.setDate(cutoff.getDate()-91);const minDay=localDay(cutoff);log.days=Object.fromEntries(Object.entries(log.days).filter(([day])=>day>=minDay));log.events=log.events.filter(event=>event.day>=minDay).slice(-800);localStorage.setItem(USAGE_KEY,JSON.stringify(log))}
function addUsageTime(kind,ms){if(!Number.isFinite(ms)||ms<=0)return;const log=readUsage(),day=localDay(),bucket=log.days[day]||{studyMs:0,playMs:0};bucket[kind==='play'?'playMs':'studyMs']=(Number(bucket[kind==='play'?'playMs':'studyMs'])||0)+Math.min(ms,15000);log.days[day]=bucket;writeUsage(log)}
function recordQuizUsage(level,totalCount,correctCount){const log=readUsage(),day=localDay(),durationMs=quizStartedAt?Math.max(0,Date.now()-quizStartedAt):0;log.events.push({day,at:new Date().toISOString(),subject,levelId:String(level.id),levelName:level.name,total:totalCount,correct:correctCount,durationMs});writeUsage(log)}
function studyUsageActive(){const course=document.getElementById('setup'),practice=document.getElementById('quizView');return !document.hidden&&((course&&!course.hidden)||(practice&&!practice.hidden))}
let studyUsageLast=Date.now(),studyUsageWasActive=studyUsageActive();
function flushStudyUsage(nextActive=studyUsageActive()){const now=Date.now();if(studyUsageWasActive)addUsageTime('study',now-studyUsageLast);studyUsageLast=now;studyUsageWasActive=nextActive}
setInterval(()=>flushStudyUsage(),5000);
document.addEventListener('visibilitychange',()=>flushStudyUsage());window.addEventListener('pagehide',()=>flushStudyUsage(false));
function usageDays(range){const todayDate=new Date(),days=[];if(range==='today')return[localDay(todayDate)];const monday=new Date(todayDate),offset=(todayDate.getDay()+6)%7;monday.setDate(todayDate.getDate()-offset);for(let i=0;i<7;i++){const day=new Date(monday);day.setDate(monday.getDate()+i);if(day<=todayDate)days.push(localDay(day))}return days}
function formatUsageTime(ms){const safe=Math.max(0,ms),seconds=Math.floor(safe/1000),minutes=Math.floor(safe/60000),hours=Math.floor(minutes/60),rest=minutes%60;if(minutes<1)return lang==='zh'?`${seconds}秒`:`${seconds}s`;if(lang==='zh')return hours?`${hours}小时${rest?rest+'分钟':''}`:`${minutes}分钟`;return hours?`${hours}h ${rest?rest+'m':''}`:`${minutes}m`}
function renderUsage(){const log=readUsage(),days=new Set(usageDays(usageRange)),totals=[...days].reduce((sum,day)=>{const d=log.days[day]||{};sum.study+=Number(d.studyMs)||0;sum.play+=Number(d.playMs)||0;return sum},{study:0,play:0}),events=log.events.filter(event=>days.has(event.day)),groups=new Map();for(const event of events){const key=`${event.subject}:${event.levelId}`,group=groups.get(key)||{...event,total:0,correct:0,sessions:0};group.total+=Number(event.total)||0;group.correct+=Number(event.correct)||0;group.sessions++;groups.set(key,group)}const zhMode=lang==='zh';usageTitle.textContent=zhMode?'学习回顾':'Learning Review';usageCopy.textContent=zhMode?'查看专注与休息时间，以及已经推进的课程阶段。':'Review focus and break time plus the course stages you moved forward.';usageTodayTab.textContent=zhMode?'今日':'Today';usageWeekTab.textContent=zhMode?'本周':'This week';usageTodayTab.classList.toggle('active',usageRange==='today');usageWeekTab.classList.toggle('active',usageRange==='week');usageSummary.innerHTML=`<div class="usage-stat"><strong>${formatUsageTime(totals.study+totals.play)}</strong><span>${zhMode?'总使用时长':'Total app time'}</span></div><div class="usage-stat"><strong>${formatUsageTime(totals.study)}</strong><span>${zhMode?'专注学习':'Focused learning'}</span></div><div class="usage-stat"><strong>${formatUsageTime(totals.play)}</strong><span>${zhMode?'休息时间':'Break time'}</span></div>`;const subjectNames={math:zhMode?'数学':'Math',english:'English',science:zhMode?'科学':'Science'};usageLevels.innerHTML=groups.size?[...groups.values()].sort((a,b)=>b.at.localeCompare(a.at)).map(group=>`<div class="usage-row"><div><strong>${subjectNames[group.subject]||group.subject} · ${esc(tx(group.levelName)||group.levelId)}</strong><small>${group.sessions} ${zhMode?'节微课':'lesson(s)'}</small></div><span>${group.total} ${zhMode?'题':'questions'}</span><span>${group.correct}/${group.total}</span></div>`).join(''):`<div class="usage-empty">${zhMode?'这个时间范围内还没有课程记录。':'No lesson records in this period yet.'}</div>`}
function openUsage(){flushStudyUsage();usageRange='today';renderUsage();usageModal.hidden=false;document.body.style.overflow='hidden'}
function closeUsage(){usageModal.hidden=true;document.body.style.overflow=''}
function setUsageRange(range){usageRange=range;renderUsage()}
