import { createHash } from 'node:crypto';
import { mkdir, realpath, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { readSourceTree, repositoryRoot } from './build-web.mjs';

const BANK_HEADER = '// Generated by tools/build-standalone-banks.mjs. Do not edit directly.\n';
const CURRICULUM_HEADER = '// Generated by tools/build-curriculum-bundle.mjs. Do not edit directly.\n';
const bundleJson = value => JSON.stringify(value).replace(/</g, '\\u003c');

// Catalog URLs are web-root-relative, as in the original loader. Never fetch them.
function localCurriculumPath(url) {
  if (typeof url !== 'string' || url.trim() !== url || /[\\:%?#\0]/.test(url)) {
    throw new Error(`Expected a plain local curriculum URL: ${url}`);
  }
  const relative = url.replace(/^\.\//, '');
  if (!relative.startsWith('data/curriculum/') || !relative.endsWith('.json') || relative.split('/').some(part => !part || part === '.' || part === '..')) {
    throw new Error(`Curriculum URL must stay inside web/data/curriculum/: ${url}`);
  }
  return relative;
}

function itemCount(shard, name) {
  if (!Array.isArray(shard.units)) throw new Error(`${name}: expected units array.`);
  let count = 0;
  for (const unit of shard.units) {
    if (!Array.isArray(unit.lessons)) throw new Error(`${name}: expected lessons array.`);
    for (const lesson of unit.lessons) {
      if (!Array.isArray(lesson.items)) throw new Error(`${name}: expected lesson items array.`);
      count += lesson.items.length;
    }
  }
  return count;
}

function serializeChangedJson(value, original) {
  const text = original.toString('utf8');
  const indent = text.match(/\n([ \t]+)"/)?.[1] || '  ';
  const newline = text.includes('\r\n') ? '\r\n' : '\n';
  const suffix = text.endsWith('\n') ? newline : '';
  return Buffer.from(JSON.stringify(value, null, indent).replace(/\n/g, newline) + suffix);
}

export async function buildData({ root = repositoryRoot, write = false } = {}) {
  const resolvedRoot = await realpath(root);
  const webRoot = path.join(resolvedRoot, 'web');
  // Reject links before reading or writing any content or generated destination.
  const files = new Map((await readSourceTree(webRoot, { ignoreMetadata: false })).map(file => [file.path, file.data]));
  const pending = new Map();
  function readJson(name) {
    const data = files.get(name);
    if (!data) throw new Error(`Missing web/${name}`);
    try { return JSON.parse(data.toString('utf8')); }
    catch (error) { throw new Error(`Invalid JSON in web/${name}: ${error.message}`); }
  }
  function stage(name, data) {
    if (!files.get(name)?.equals(data)) pending.set(name, data);
  }

  const banks = {};
  for (const subject of ['math', 'english', 'science']) {
    const bank = readJson(`data/${subject}.json`);
    if (bank.subject !== subject || bank.mode !== 'normal' || !Array.isArray(bank.levels)) {
      throw new Error(`data/${subject}.json must be a normal ${subject} question bank.`);
    }
    banks[`${subject}:normal`] = bank;
  }
  stage('src/generated/question-banks.js', Buffer.from(`${BANK_HEADER}globalThis.__NAMELESS_QUESTION_BANKS__=${bundleJson(banks)};\n`));

  const catalog = readJson('data/curriculum/catalog.v3.json');
  if (catalog.schemaVersion !== 3 || !Array.isArray(catalog.packages)) throw new Error('Expected a V3 curriculum catalog with packages.');
  const documents = Object.create(null);
  const visited = new Set();
  for (const entry of catalog.packages) {
    const manifestPath = localCurriculumPath(entry.manifestUrl);
    if (visited.has(manifestPath)) throw new Error(`Duplicate curriculum manifest: ${manifestPath}`);
    visited.add(manifestPath);
    const manifest = readJson(manifestPath);
    if (manifest.schemaVersion !== 3 || manifest.id !== entry.id || !Array.isArray(manifest.shards)) {
      throw new Error(`Invalid V3 curriculum manifest: ${manifestPath}`);
    }
    documents[entry.manifestUrl] = manifest;
    let changedManifest = false;
    for (const reference of manifest.shards) {
      const shardPath = localCurriculumPath(reference.url);
      if (visited.has(shardPath)) throw new Error(`Duplicate curriculum document: ${shardPath}`);
      visited.add(shardPath);
      const shard = readJson(shardPath);
      if (shard.schemaVersion !== 3 || shard.packageId !== manifest.id) throw new Error(`Shard package does not match its manifest: ${shardPath}`);
      const sha256 = createHash('sha256').update(files.get(shardPath)).digest('hex');
      const count = itemCount(shard, shardPath);
      if (reference.sha256 !== sha256 || reference.itemCount !== count) {
        reference.sha256 = sha256;
        reference.itemCount = count;
        changedManifest = true;
      }
      documents[reference.url] = shard;
    }
    // Preserve every byte of unmodified manifests, including their formatting.
    if (changedManifest) stage(manifestPath, serializeChangedJson(manifest, files.get(manifestPath)));
  }
  stage('src/generated/curriculum-content.js', Buffer.from(`${CURRICULUM_HEADER}globalThis.__GOTIT_CURRICULUM_V3__=${bundleJson({ catalog, documents })};\n`));

  // All inputs and paths are validated before the first write. Default is read-only.
  if (write) {
    for (const [name, data] of pending) {
      const destination = path.join(webRoot, name);
      await mkdir(path.dirname(destination), { recursive: true });
      await writeFile(destination, data);
    }
  }
  return { changedFiles: [...pending.keys()], writtenFiles: write ? [...pending.keys()] : [], bankCount: Object.keys(banks).length, curriculumDocuments: Object.keys(documents).length };
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  const args = process.argv.slice(2);
  if (args.some(arg => !['--write', '--check'].includes(arg)) || (args.includes('--write') && args.includes('--check'))) {
    console.error('Usage: node tools/build-data.mjs [--check | --write]');
    process.exitCode = 1;
  } else {
    buildData({ write: args.includes('--write') }).then(result => {
      if (result.changedFiles.length) {
        console.log(`${args.includes('--write') ? 'Updated' : 'Out of date'}:\n${result.changedFiles.map(name => `  web/${name}`).join('\n')}`);
        if (!args.includes('--write')) { console.log('Run npm run build:data to regenerate these files.'); process.exitCode = 1; }
      } else console.log(`Generated data is current: ${result.bankCount} question banks and ${result.curriculumDocuments} curriculum documents; no files changed.`);
    }).catch(error => { console.error(error.message); process.exitCode = 1; });
  }
}
